FROM docker.io/library/eclipse-temurin:11-jre-alpine

RUN apk update && apk upgrade && \
    apk add \
        gtk+2.0 \
        libxtst \
        xf86-video-dummy \
        xorg-server

COPY COPY /

CMD Xorg > /dev/null 2>&1 & \
    export DISPLAY=:0 && \
    cd /tmp && java Verify && \
    kill $(pidof Xorg)
