# https://quarkus.io/guides/logging#json-logging
quarkus.log.console.json.log-format=ecs
quarkus.log.console.json.pretty-print=false
# https://quarkus.io/guides/opentelemetry#disable-all-or-parts-of-the-opentelemetry-extension
quarkus.otel.traces.enabled=false
quarkus.otel.metrics.enabled=false
quarkus.otel.logs.enabled=false

#quarkus.log.category."org.acme.fruit".level=TRACE
#quarkus.log.category."org.acme.fruit".min-level=TRACE

