# https://quarkus.io/guides/config-reference#configuration-reference
quarkus.config.locations=/deployments/config/secrets.properties

# https://quarkus.io/guides/datasource#jdbc-configuration
quarkus.datasource.username=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/quarkus

# https://quarkus.io/guides/opentelemetry
quarkus.otel.exporter.otlp.endpoint=http://agent:4317/

# https://quarkus.io/guides/kafka
kafka.bootstrap.servers=kafka:29092
