ARG BASE_IMAGE

FROM ${BASE_IMAGE} AS base

RUN apk add bash curl gawk openssl valgrind vim && \
    addgroup -S otel && adduser -S otel -G otel

FROM base AS build

RUN apk add cmake gcc g++ make openssl-dev

USER otel
WORKDIR /home/otel

COPY . .

RUN cmake -S . -B alpine && \
    cmake --build alpine --clean-first

FROM base

COPY --from=build /usr/lib/libgcc_s.so.1 /usr/lib/
COPY --from=build /usr/lib/libtsan.so.2.0.0 /usr/lib/
COPY --from=build /home/otel/alpine/client /usr/bin/
COPY --from=build /home/otel/alpine/libmiddleware.so /usr/lib/
COPY --from=build /home/otel/alpine/producer /usr/bin/
COPY --from=build /home/otel/alpine/server /usr/bin/

RUN ln -s /usr/lib/libgcc_s.so.1 /usr/lib/libgcc_s.so && \
    ln -s /usr/lib/libtsan.so.2.0.0 /usr/lib/libtsan.so.2 && \
    ln -s /usr/lib/libtsan.so.2 /usr/lib/libtsan.so

USER otel
WORKDIR /home/otel
