%dev.quarkus.log.json.console.enabled=false

app.generator.enabled=true
app.punctuation.enabled=false

quarkus.kafka.devservices.enabled=false
#quarkus.kafka.devservices.container-env.KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
#quarkus.kafka.devservices.topic-partitions.ping=1

mp.messaging.outgoing.ping.connector=smallrye-kafka
mp.messaging.outgoing.ping.merge=true
mp.messaging.outgoing.ping.topic=ping

quarkus.http.host=0.0.0.0
#quarkus.http.port=8080

#
# https://quarkus.io/guides/kafka-streams#configuration-reference
#
quarkus.kafka-streams.topics=ping
# https://kafka.apache.org/23/streams/developer-guide/config-streams/#applicationid
# This ID is used in the following places to isolate resources used by the application from others:
# * As the default Kafka consumer and producer client.id prefix
# * As the Kafka consumer group.id for coordination
# * As the name of the subdirectory in the state directory (cf. state.dir)
# * As the prefix of internal Kafka topic names
quarkus.kafka-streams.application-id=abc

# pass-through options
#kafka-streams.state.dir=
#kafka-streams.cache.max.bytes.buffering=10240
#kafka-streams.commit.interval.ms=1000
#kafka-streams.metadata.max.age.ms=500
#kafka-streams.auto.offset.reset=earliest
#kafka-streams.metrics.recording.level=DEBUG
